table Painel
	lineageTag: 7f8a9b0c-1d2e-3f4a-5b6c-7d8e9f0a1b2c

	column Medida
		dataType: string
		lineageTag: 8a9b0c1d-2e3f-4a5b-6c7d-8e9f0a1b2c3d
		summarizeBy: none
		sourceColumn: Medida
		sortByColumn: ID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 9b0c1d2e-3f4a-5b6c-7d8e-9f0a1b2c3d4e
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition Painel = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(
				        {
				            {"(+) Receita Bruta de Vendas", 1},
				            {"(-) Deduções sobre Vendas", 2},
				            {"(=) Receita Líquida", 3},
				            {"(-) CMV", 4},
				            {"(=) Lucro Bruto", 5},
				            {"(-) Despesas Operacionais", 6},
				            {"(-) Despesas Financeiras", 7},
				            {"(+) Receitas Financeiras", 8},
				            {"(=) Resultado do Período", 9},
				            {"Margem Bruta %", 10},
				            {"Margem Líquida %", 11},
				            {"Margem CMV %", 12},
				            {"Receita Bruta MoM %", 13},
				            {"Resultado MoM %", 14}
				        },
				        {"Medida", "ID"}
				    ),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Medida", type text}, {"ID", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

